# pkgdown.yaml
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.

      - name: Build site
        run: |
          # Make sure to specify output directory for pkgdown
          # Default build_site() puts site in `docs/`
          # We want `docs/pkgdown`, so set the destination in `_pkgdown.yml` or move it after build.
          # If pkgdown doesn't natively support subfolders, just build as normal and then move it:
          pkgdown::build_site()
          dir.create("docs/pkgdown", showWarnings = FALSE)
          file.rename("docs/index.html", "docs/pkgdown/index.html")
          # Move all built site files into docs/pkgdown
          # This might require adjusting depending on your pkgdown structure:
          # For example, if pkgdown by default places everything in docs:
          system("cp -r docs/* docs/pkgdown/")
          system("rm -rf docs/*")
          # Now docs/pkgdown contains the pkgdown site

      - name: Deploy pkgdown to GitHub Pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          clean: false
          branch: gh-pages
          folder: docs/pkgdown
